### ISSUE TITLE
Can we support SoundCloud's API alongside YouTube's API?

### ISSUE THREAD

**Issue by MeoMix** [MeoMix/Streamus#8]
A lot of songs found on SoundCloud are not found on YouTube. It would be nice to increase the songs allowed to be played on Streamus by supporting SoundCloud.

**Comment by stagl** [comment]
so, still no resolution on this? soundcloud is a huge platform that is being looked over, but why?

**Comment by MeoMix** [comment]
Because I still need to finalize changes to Streamus to be compliant
with YouTube's TOS first? And I don't get paid to develop this / add
features?

**Comment by stagl** [comment]
I deleted my question to you a few minutes after answering because I didn't
see that the project had moved over to the streamus plugin. I apologize if
I offended you and sounded like a jerk. I wish that I would have discovered
your other project before commenting.

http://www.staglicious.com/
